version: 2

models:
  - name: data_pemain
    description: "A starter dbt model"
    columns:
      - name: nama
        description: "The primary key for this table"
        tests:
          - unique
          - not_null